# Create folder (protected) — include Authorization header
# Make sure to set `@jwt = <access_token>` (see sign-in request)
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYTBlZDA2NS1hMTcwLTRhYTgtYThiNC0wNzQxNDFhZjhhOTMiLCJlbWFpbCI6InRlc3Q1QGdtYWlsLmNvbSIsImlhdCI6MTc2NzE3NzI4MiwiZXhwIjoxNzY3MTgwODgyfQ.7Si8UpddbJ5AGPsFvnCkujRZ_B50iUeEs2U5kATOeH4
POST http://localhost:3000/folders
Authorization: Bearer {{jwt}}
Content-Type: application/json
{
  "name": "Components",
  "parentId": "9eb78839-4747-437c-9d45-2b8e8e03d9d4"
}